title: John's Example Github Page
author: John Ball
email: john.ball624@my.tccd.edu
description: > # this means to ignore newlines until "baseurl:"
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Etiam ullamcorper, lorem dictum ultricies rhoncus, eros nulla imperdiet tortor, eget commodo metus odio in eros.
Ut sollicitudin euismod blandit.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
